### PR TITLE
Fix tutorial modal not loading - id wrong

### PR DESCRIPTION
**Pull request by portableant**

### CODE REVIEW

**Comment by portableant** [comment]
Everything seems to work now. Super. :+1:

**Comment by ahb108** [comment]
Do we have have room on AWS for me to upload pdfs?

**Comment by portableant** [comment]
AWS space is unlimited, I just pay more. Just add them.

**Comment by ahb108** [comment]
OK, will upload overnight and hope we get a go ahead to launch this.

**Pull request merged**
